import type React from "react"
import type { Metadata } from "next"
import "./globals.css"
import { AppProviders } from "@/providers/AppProviders"
import { fontVariables } from "@/lib/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es" className={fontVariables}>
      <body>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  )
}
